on:
  push:
    branches: ["main", "feedback", "lecture/*"]
permissions:
  id-token: write # to verify the deployment originates from an appropriate source
  pages: write # to deploy to Pages
  contents: read # to checkout private repositories
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22.x, cache: "npm" }
      - run: npm ci
      - run: npm run build
      - run: npm test
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
          name: github-pages-artifact
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-artifact
